spring:
  application:
    name: SpringApplicationAAD
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/25b10c2f-2713-4420-89bf-fedcd080ad45/
          audiences: 00000003-0000-0000-c000-000000000000
#          jwk-set-uri:
#          issuer-uri: https://login.microsoftonline.com/fc3d9d0d-2812-4fa8-8641-a73e6bd59029/v2.0
#          audiences: 7a70de09-a2f9-4263-ba17-3d59b926e89b
logging:
  level:
    ROOT: debug